### PR TITLE
Support for Duke WeightedLevenshtein comparator

### PR DESCRIPTION
**Pull request by ghost**
A simple conditional when creating the comparator. If it sees the WeightedLevenshtein comparator is requested, creates it as well as an estimator and passes the parameters to the estimator instead of the comparator.

### CODE REVIEW

**Comment by YannBrrd** [comment]
Hi,

Thanks for PR. Having a look at it ATM. :+1:

**Comment by YannBrrd** [comment]
Wondering if we should not have something a bit more generic. Will work on this. Idea : add detection and instantiation of custom estimator in a generic way (just like comparator & cleaners). What do you think ? (cf. https://github.com/larsga/Duke/blob/master/duke-core/src/test/resources/config-custom-estimator.xml)

**Comment by edolix** [comment]
Hi @YannBrrd , 

any update on this PR?

**Comment by edolix** [comment]
Thanks for this guys!!

**Pull request merged**
